<a href="https://colab.research.google.com/github/kay-kay-t/CodingDojo/blob/main/Introduction_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


1) The selling price of 3 items at the bake sale are: \$2 for a brownie, \$1 for a cookie, $10 for a cake.

In [2]:
# Price list:
price = [2, 1, 10]
type(price)

list

The club sells 17 brownies, 40 cookies, and 1 cake.  

In [3]:
# Quantity list:
quantity_sold = [17, 40, 1]
type(quantity_sold)

list

In [4]:
# Converting a list to a NumPy Array
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
type(price_array)

numpy.ndarray

In [5]:
# Money collected for each type of item
price_array * quantity_sold_array

array([34, 40, 10])

In [6]:
# To find a profit of each item
cost_array = np.array([0.25, 0.50, 5.00])
profit_array = price_array - cost_array
print(profit_array)

[1.75 0.5  5.  ]


In [7]:
# Elementwise Booleans
profit_array > 2.00

array([False, False,  True])

The club will also sell pies for $7 so we need to update our price_array.

In [8]:
# Appending
price_array = price_array + [7] # wrong way
print(price_array)

[ 9  8 17]


In [9]:
price_array = price_array - [7]

price_array = np.append(price_array, 7)
print(price_array)

[ 2  1 10  7]


The club want to add the following prices:  \$4.50 for fudge, \$3 for a cupcake, \$4 for a loaf of banana bread, and $9 for a torte.

In [10]:
price_array = np.append(price_array, [4.50, 3, 4, 9])
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


It turns out nobody plans to make a torte, so they want to remove the price of that item from the array.

In [11]:
# Deleting
price_array = np.delete(price_array, -1)
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4. ]


Next the club decides to raise the price of cakes from \$10 to $12. 

In [12]:
# Replacing
price_array[2] = 12
print(price_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]


2) Update the  quantity_sold_array to include the sale of 2 pies,  3 trays of fudge, 16 cupcakes, and 5 loaves of banana bread.  You also realize that one of the cookies you thought was sold had actually fallen on the ground, so edit the quantity_sold_array from 40 to 39.  

In [13]:
# Updating quantity
quantity_sold_array = np.append(quantity_sold_array, [2, 3, 16, 5])
# Editing quantity of cookies sold
quantity_sold_array[1] = 39
print(quantity_sold_array)

[17 39  1  2  3 16  5]


3) Determine the amount of money collected from the sale of each item at the bake sale.  

In [16]:
# How much was made from the sale of each item
gross = price_array * quantity_sold_array
print(gross)

[34.  39.  12.  14.  13.5 48.  20. ]


4) Create a NumPy array "quantity_leftover" that includes the quantity of each item remaining at the end of the sale: 2 cakes, 1 pie, 6 trays of fudge, 2 loaves of banana bread.  Hint: Make sure to include "0" for any item that was sold out. Why is this important when creating the array?

In [17]:
quantity_leftover = np.array([0, 0, 2, 1, 6, 0, 2])
print(quantity_leftover)

[0 0 2 1 6 0 2]


5) The club decides to sell the leftover items at half price and everything quickly sells out!  Determine how much money was collected from the clearance sale.  

In [28]:
# Finding half price of items
half_price = price_array / 2
print(half_price)
# Finding how much we made seling leftovers for half price
clearance_gross = quantity_leftover * half_price
print(clearance_gross)

[1.   0.5  6.   3.5  2.25 1.5  2.  ]
[ 0.   0.  12.   3.5 13.5  0.   4. ]


6) How much total money was collected from the bake sale (including the sale of full price and clearance items)

In [31]:
total = np.sum(gross + clearance_gross)
print(total)

213.5
